### ISSUE TITLE
Typo in work page

### ISSUE THREAD

**Issue by Vyvy-vi** [oke-aditya/me#16]
## 🐛 Bug
**Describe the bug**
There's a typo in point 2 of the `Work` page

![Developed typoed as Dveloped](https://cdn.discordapp.com/attachments/735506302784110652/796418095777579029/Screenshot_2021-01-06_at_10.10.40_PM.png)

**Possible Fix**
`Developed`

**Comment by oke-aditya** [comment]
Yep Let's fix it :smiley:
