### ISSUE TITLE
changing endpoint for this portfolio site

### ISSUE THREAD

**Issue by 1UC1F3R616** [oke-aditya/me#4]
Issue-Type: Suggestion

Thanks for finding this amazing template!

- I believe this site should not be on `/me` endpoint but on `/`

**Comment by oke-aditya** [comment]
Yeah but how do you fix it ?
I could create a repo with name `oke-aditya.github.io` but that will not allow me to use CI CD pipeline.
Plus I have URL shortener for this as `bit.ly/oke_aditya` (which is what people will use)

The endpoint I don't find a solution, do let me know if you have one.

**Comment by 1UC1F3R616** [comment]
- we can't set CI CD pipeline with `username.github.io`?
- URL shortener or using the domain name is always an option, but when we visit someones GitHub the first URL that's hit is `username.github.io` usually, maybe then a redirect can be added to there.
    - create `index.html` file
    - add this inside script `window.location.replace("http://www.w3schools.com");`
- Also what CI CD pipelines are you using?

**Comment by oke-aditya** [comment]
Since Jekyll build and run is run over GitHub, the site is built over github pages in gh-pages branch where I don't even push.
I don't push the site to master as you see.

I possibility is to setup username.github.io and add a CNAME to redirect to `/me` so both point same.
